// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `truncate_char_boundary`

/// Copy an existing history item to the OS clipboard (text / rich / image),
/// marking it self-written so the poll loop does not re-record it.
Future<void> copyToClipboard({required BigInt id}) =>
    RustLib.instance.api.crateApiClipboardCopyToClipboard(id: id);

/// Forward a frontend log line into the shared `cliphist.log`. Truncated to a
/// UTF-8 char boundary so non-ASCII (e.g. Chinese) logs do not panic when
/// slicing by byte index.
Future<void> feLog({required String message}) =>
    RustLib.instance.api.crateApiClipboardFeLog(message: message);

/// Simulate a Ctrl+V (Windows) / Cmd+V (macOS) / evdev-injected (Linux) paste
/// into the previously-focused window. Delegates to the platform paste engine
/// — Windows + macOS use `rdev::simulate`, Linux routes through the privileged
/// evdev helper. Returns `Err` on platforms without paste support or if the
/// synthetic event fails, so the Dart side surfaces it rather than a silent
/// no-op.
Future<void> simulatePasteCmd() =>
    RustLib.instance.api.crateApiClipboardSimulatePasteCmd();
