// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/clipboard_engine.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Full in-memory history, newest first. Synchronous (cheap lock + clone).
List<ClipboardItem> getHistory() =>
    RustLib.instance.api.crateApiHistoryGetHistory();

/// Move an existing history item to the front (most-recently-used first) and
/// persist the new order. Triggered by the frontend's number-key quick-paste
/// (1-9) so the just-used entry floats to the top. Other copy actions
/// (double-click, copy button, Enter) intentionally do NOT reorder.
Future<void> moveToTop({required BigInt id}) =>
    RustLib.instance.api.crateApiHistoryMoveToTop(id: id);

Future<void> deleteItem({required BigInt id}) =>
    RustLib.instance.api.crateApiHistoryDeleteItem(id: id);

Future<void> clearHistory() =>
    RustLib.instance.api.crateApiHistoryClearHistory();

/// Load an item's image PNG bytes on demand (FRB maps `Vec<u8>` to `Uint8List`
/// zero-copy). `None` for non-image items or missing files. Only the currently
/// visible images are fetched, keeping memory low.
Future<Uint8List?> getImageData({required BigInt id}) =>
    RustLib.instance.api.crateApiHistoryGetImageData(id: id);
