// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the Rust core: load history + settings, install the panic hook,
/// stash the global [`AppState`], and spawn the four background tasks
/// (clipboard poll, window-action worker, helper-status monitor, expired-item
/// cleaner). Idempotent-ish: a second call is a no-op (the [`OnceLock`] guards
/// the state), so it is safe if Dart retries after a hot restart.
Future<void> initAppState() => RustLib.instance.api.crateApiInitInitAppState();
