// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/settings_store.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// In-memory settings (single source of truth). Synchronous.
Settings getSettings() => RustLib.instance.api.crateApiSettingsGetSettings();

/// Apply a partial settings patch transactionally. Validation happens against
/// a clone first, so an invalid multi-field patch cannot partially mutate the
/// in-memory settings. The file is saved before the shared snapshot is swapped
/// and before the double-tap side effect is applied.
Future<Settings> updateSettings({required SettingsPatch patch}) =>
    RustLib.instance.api.crateApiSettingsUpdateSettings(patch: patch);

/// Is `hotkey` a syntactically valid global shortcut? Synchronous.
bool validateHotkey({required String hotkey}) =>
    RustLib.instance.api.crateApiSettingsValidateHotkey(hotkey: hotkey);
