// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/settings_store.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// In-memory settings (single source of truth). Synchronous.
Settings getSettings() => RustLib.instance.api.crateApiSettingsGetSettings();

/// Apply a partial settings patch. Type-safe field extraction via
/// [`SettingsPatch`]; bounded numeric fields are clamped; side-effecting
/// fields (autostart, hotkey registration, double-tap listener) are validated
/// here but their OS-level effects are wired in M5/M7/M8 respectively — M2
/// persists the value and logs the deferral.
Future<Settings> updateSettings({required SettingsPatch patch}) =>
    RustLib.instance.api.crateApiSettingsUpdateSettings(patch: patch);

/// Is `hotkey` a syntactically valid global shortcut? Synchronous.
bool validateHotkey({required String hotkey}) =>
    RustLib.instance.api.crateApiSettingsValidateHotkey(hotkey: hotkey);
