// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Round-trip: return a stub history list.
List<String> getHistory() => RustLib.instance.api.crateApiSpikeGetHistory();

/// Round-trip: validate error path (empty id rejected).
Future<void> copyToClipboard({required String id}) =>
    RustLib.instance.api.crateApiSpikeCopyToClipboard(id: id);

/// Round-trip: echo the patch back so Dart can confirm it arrived intact.
Future<String> updateSettings({required String patch}) =>
    RustLib.instance.api.crateApiSpikeUpdateSettings(patch: patch);

/// Event stream: push `tick N` every 500ms. Dart subscribes and must see the
/// first event within 1s. This stands in for the real `clipboard-changed` stream.
Stream<String> streamClipboardChanged() =>
    RustLib.instance.api.crateApiSpikeStreamClipboardChanged();
