// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/clipboard_engine.dart';
import '../core/events.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Top-5 clipboard snapshot after a new entry is recorded.
Stream<List<ClipboardItem>> streamClipboardChanged() =>
    RustLib.instance.api.crateApiStreamStreamClipboardChanged();

/// Full history snapshot, pushed when items are removed anywhere in the list
/// (retention sweep).
Stream<List<ClipboardItem>> streamHistoryReplace() =>
    RustLib.instance.api.crateApiStreamStreamHistoryReplace();

/// The id of the item just floated to the front by `move_to_top`.
Stream<BigInt> streamItemMovedToTop() =>
    RustLib.instance.api.crateApiStreamStreamItemMovedToTop();

/// Whether the privileged evdev double-tap helper is authorized/connected.
Stream<bool> streamHelperStatus() =>
    RustLib.instance.api.crateApiStreamStreamHelperStatus();

/// Window-action request (the Rust core owns no window handle). Dart performs
/// the always-on-top restack dance on receipt.
Stream<WindowActionKind> streamWindowAction() =>
    RustLib.instance.api.crateApiStreamStreamWindowAction();

/// Reliable UI-isolate hand-off for native hotkey/double-tap/single-instance
/// wake requests. The stream above remains for compatibility, while the Dart
/// controller uses this synchronous coalescing poll on desktop platforms.
bool takePendingWindowAction() =>
    RustLib.instance.api.crateApiStreamTakePendingWindowAction();
