// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ClipboardItem {
  final BigInt id;
  final String content;
  final String contentType;
  final String timestamp;
  final String preview;
  final BigInt charCount;

  /// Path (relative to the ClipHist data dir) of the external PNG file.
  /// Replaces the old inline base64 `image_data` so the JSON stays small
  /// and images are loaded on demand. `None` for non-image items.
  final String? imagePath;
  final int? imageWidth;
  final int? imageHeight;
  final String? htmlContent;

  /// Stable content identity used for whole-history deduplication. Optional
  /// on disk for migration from releases that predate this field.
  final String? contentHash;

  const ClipboardItem({
    required this.id,
    required this.content,
    required this.contentType,
    required this.timestamp,
    required this.preview,
    required this.charCount,
    this.imagePath,
    this.imageWidth,
    this.imageHeight,
    this.htmlContent,
    this.contentHash,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      content.hashCode ^
      contentType.hashCode ^
      timestamp.hashCode ^
      preview.hashCode ^
      charCount.hashCode ^
      imagePath.hashCode ^
      imageWidth.hashCode ^
      imageHeight.hashCode ^
      htmlContent.hashCode ^
      contentHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClipboardItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          content == other.content &&
          contentType == other.contentType &&
          timestamp == other.timestamp &&
          preview == other.preview &&
          charCount == other.charCount &&
          imagePath == other.imagePath &&
          imageWidth == other.imageWidth &&
          imageHeight == other.imageHeight &&
          htmlContent == other.htmlContent &&
          contentHash == other.contentHash;
}
