// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Settings {
  final bool closeToTray;
  final double zoomLevel;
  final String hotkey;
  final bool autoStart;
  final bool silentStart;
  final String doubleTapKey;
  final int retentionDays;
  final int windowWidth;
  final int windowHeight;
  final bool windowUserResized;

  const Settings({
    required this.closeToTray,
    required this.zoomLevel,
    required this.hotkey,
    required this.autoStart,
    required this.silentStart,
    required this.doubleTapKey,
    required this.retentionDays,
    required this.windowWidth,
    required this.windowHeight,
    required this.windowUserResized,
  });

  @override
  int get hashCode =>
      closeToTray.hashCode ^
      zoomLevel.hashCode ^
      hotkey.hashCode ^
      autoStart.hashCode ^
      silentStart.hashCode ^
      doubleTapKey.hashCode ^
      retentionDays.hashCode ^
      windowWidth.hashCode ^
      windowHeight.hashCode ^
      windowUserResized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Settings &&
          runtimeType == other.runtimeType &&
          closeToTray == other.closeToTray &&
          zoomLevel == other.zoomLevel &&
          hotkey == other.hotkey &&
          autoStart == other.autoStart &&
          silentStart == other.silentStart &&
          doubleTapKey == other.doubleTapKey &&
          retentionDays == other.retentionDays &&
          windowWidth == other.windowWidth &&
          windowHeight == other.windowHeight &&
          windowUserResized == other.windowUserResized;
}

/// A partial update to [`Settings`]. Every field is optional so the frontend
/// can send only the keys it wants to change. `update_settings` deserializes
/// its payload directly into this struct, which makes field extraction
/// type-safe — no manual `serde_json::Value::get` + `as_*` casting.
class SettingsPatch {
  final bool? closeToTray;
  final double? zoomLevel;
  final String? hotkey;
  final bool? autoStart;
  final bool? silentStart;
  final String? doubleTapKey;
  final int? retentionDays;
  final int? windowWidth;
  final int? windowHeight;
  final bool? windowUserResized;

  const SettingsPatch({
    this.closeToTray,
    this.zoomLevel,
    this.hotkey,
    this.autoStart,
    this.silentStart,
    this.doubleTapKey,
    this.retentionDays,
    this.windowWidth,
    this.windowHeight,
    this.windowUserResized,
  });

  @override
  int get hashCode =>
      closeToTray.hashCode ^
      zoomLevel.hashCode ^
      hotkey.hashCode ^
      autoStart.hashCode ^
      silentStart.hashCode ^
      doubleTapKey.hashCode ^
      retentionDays.hashCode ^
      windowWidth.hashCode ^
      windowHeight.hashCode ^
      windowUserResized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsPatch &&
          runtimeType == other.runtimeType &&
          closeToTray == other.closeToTray &&
          zoomLevel == other.zoomLevel &&
          hotkey == other.hotkey &&
          autoStart == other.autoStart &&
          silentStart == other.silentStart &&
          doubleTapKey == other.doubleTapKey &&
          retentionDays == other.retentionDays &&
          windowWidth == other.windowWidth &&
          windowHeight == other.windowHeight &&
          windowUserResized == other.windowUserResized;
}
